language: java
deploy:
  on:
    branch: main
  skip_cleanup: true
  provider: heroku
  app: servidor-hectorfr95
  api_key:
    secure: KjVovGp4UKwVkRvnWuIMxSHGvMGbtliodfIXHByi20HeEt7+jTFEldGoomiIH2dG8dMnjitgNSIlCLg/xf1qe4lokuh80XdlAGn98njBhrFSWVslnsWmaj86nFWKY5NLNwaIpQJ/VJDLmnkBqsGVatJqSTYwMW6w5J6uoVd1D3WPMyKLGlzLLmRVbSNHflh1hsv0uk0zEa/q+zTvrtBCitLRU8f4TvTfPpjLKxPaPrrCXsxmHWdsquS63m5lcZeUqQZIRfvJ8ZQGKIEQBBktXRk5gOHnGWvdMg7Yonr3AbdMp0CeGIb2v6Gom9Q96MOQZ65bWscN8kzzqtx9D9bH64DVcf7l7125V5WbCWyYwjUsIlZx9O3pIikfRIsen8ZfNtryOH2NOmXrAa9YjHknQiq84suEy5SSTUScQnk2Qs0v+MLMAYkZkzG7RznDL/72HGzlnH1O9mBZKxoMUnJonYAQQ96EiysaGmSMbdMw+B6glChVlvPthwez975xKfEWMGSorwern0Z48kTz7QzuGxHkmv4aq66qCikvZMKs5k8KTKlvk/J3vPycJaZVr+Ty8Onaue6VnEKHYllmBr4jyOEPM4ZIrUF+QPNNw/JO5gKe0RWAifieCSWuvq81chFH2c/hEIY3XyVI/tKsVrqaZnn2QOWpnjtZCshAO/u6GgM=
